theme: jekyll-theme-minimal
title: "Prospective Despair: Season 1 -  A New Direction Archive"
logo: https://cdn.discordapp.com/attachments/465547475839746058/857298482933923840/PDLogoANewDirectionTransparent.png
