theme: jekyll-theme-minimal
title: "Prospective Despair: Season 1 -  A New Direction Archive"
logo: https://cdn.discordapp.com/attachments/786958581647278130/857295681836285962/PDLogoANewDirection.png
